[package]
name = "futures-compat"
version = "0.0.1"
description = "A compatibility layer between different versions of Future."
authors = ["Sean McArthur <sean@seanmonstar.com>"]
license = "MIT"

[dependencies]
futures-v01x = "0.1"
futures-v02x = "0.1"
tokio-io = "0.1.6"
